import { Poppins } from "next/font/google";
import "./globals.scss";
import NavBar from "@/Component/NavBar/NavBar";

const poppins = Poppins({ 
  subsets: ["latin"],
weight : ["300","400","600","700","800","900"]
});

export const metadata = {
  title: "Portfolio Smith",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="container">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
